name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  Grading:
    name: Testing code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bf591-r/bf591-r-docker:latest
      volumes:
        - .:/github/workspace
    steps:
      - name: checkout submission
        uses: actions/checkout @v4
        with:
            repository: ${{ github.repository }}
            path: submission
      - name: checkout template tests
        uses: actions/checkout @v4
        with:
            repository: BF591-R/test-assignment
            path: template
      - name: run tests
        run: bash /entrypoint.sh test submission/main.R template/test_main.R test_results.csv
      - name: upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
      - uses: education/autograding@v1

